/**
 * Shared contracts for the Sudoku platform.
 * All teams import these types to ensure a single source of truth for request
 * and response payloads as well as domain entities.
 *
 * The file is compiled with `strict` enabled.
 */

/**
 * Core domain value types – the canonical definitions used across services.
 */
export enum Difficulty {
  Easy = "easy",
  Medium = "medium",
  Hard = "hard",
}

/**
 * A Sudoku cell value. `0` represents an empty cell.
 */
export type CellValue = 0 | 1 | 2 | 3 | 4 | 5 | 6 | 7 | 8 | 9;

/**
 * A 9×9 Sudoku board. The outer array represents rows, the inner array columns.
 * The type does not enforce length at compile‑time, but runtime code can rely on
 * the contract that each board is a 9×9 matrix of {@link CellValue}.
 */
export type Board = CellValue[][];

/**
 * The puzzle entity generated by the Puzzle Service. It contains the initial board
 * presented to the player and the full solution for validation purposes.
 */
export interface Puzzle {
  /** The board presented to the player – cells with `0` are empty. */
  board: Board;
  /** The complete solution for the puzzle. */
  solution: Board;
  /** Difficulty level of the puzzle. */
  difficulty: Difficulty;
}

/**
 * A score entry stored by the Scores Service.
 */
export interface ScoreEntry {
  /** Player's display name. */
  playerName: string;
  /** Difficulty of the puzzle that was solved. */
  difficulty: Difficulty;
  /** Time taken to solve the puzzle, in seconds. */
  timeToSolve: number;
  /** ISO‑8601 timestamp when the score was recorded. */
  solvedAt: string;
}

/**
 * The leaderboard derived from stored scores – up to ten entries per difficulty.
 */
export interface Leaderboard {
  /** Difficulty for which this leaderboard is generated. */
  difficulty: Difficulty;
  /** Ordered list of the best scores (fastest first). */
  entries: ScoreEntry[];
}

/**
 * Generic error response used by any service.
 */
export interface ErrorResponse {
  /** Human‑readable error message. */
  message: string;
  /** Optional numeric error code. */
  code?: number;
}

/**
 * ---------------------------------------------------------------------------
 * API request / response contracts – built from the domain types above.
 * ---------------------------------------------------------------------------
 */

/** Request payload for GET /puzzle – expressed as a query parameter. */
export interface GetPuzzleRequest {
  /** Desired difficulty level. */
  difficulty: Difficulty;
}

/** Response payload for GET /puzzle. */
export interface GetPuzzleResponse {
  /** The initial board for the requested puzzle. */
  board: Board;
  /** Difficulty echoed back for convenience. */
  difficulty: Difficulty;
}

/** Request payload for POST /validate. */
export interface ValidateRequest {
  /** The board submitted by the client for validation. */
  board: Board;
}

/** Response payload for POST /validate. */
export interface ValidateResponse {
  /** True when the submitted board matches the solution and is uniquely solvable. */
  isCorrect: boolean;
}

/** Request payload for POST /scores. */
export interface ScoreSubmission {
  /** Player's name. */
  playerName: string;
  /** Difficulty of the puzzle that was solved. */
  difficulty: Difficulty;
  /** Time taken to solve, in seconds. */
  timeToSolve: number;
}

/** Response payload for POST /scores. */
export interface ScoreResponse {
  /** Simple status indicator – e.g., "ok" or "error". */
  status: string;
}

/** Response payload for GET /leaderboard. */
export interface LeaderboardResponse {
  /** Up to ten best scores for the requested difficulty. */
  entries: ScoreEntry[];
}

/**
 * Export a union type that aggregates all possible error responses – useful for
 * generic error handling middleware.
 */
export type ServiceError = ErrorResponse;

/**
 * Re‑export the core domain types for convenience when importing from the
 * contracts package.
 */
// Removed redundant re-export that conflicted with prior declarations.
